# Generated by Django 4.1.1 on 2022-10-12 11:13

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_ru',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_uz',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='static/db/products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='line',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='line_ru',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='line_uz',
            field=tinymce.models.HTMLField(),
        ),
    ]
