# Generated by Django 4.1.1 on 2022-09-30 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('title', models.CharField(max_length=300)),
                ('subtitle', models.TextField()),
                ('body', models.TextField()),
                ('blog_image', models.ImageField(upload_to='static/blog_images/')),
                ('slug', models.CharField(blank=True, max_length=300)),
            ],
        ),
    ]
