# Generated by Django 4.1.1 on 2022-10-10 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_blog_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='body',
            new_name='body_uz',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='subtitle',
            new_name='subtitle_uz',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='title',
            new_name='title_uz',
        ),
    ]
