# Generated by Django 4.1.1 on 2022-10-10 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_blog_body_en_blog_body_ru_blog_subtitle_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='subtitle_en',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='subtitle_ru',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='subtitle_uz',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
